service: playroll

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-west-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  graphql:
    vpc:
      securityGroupIds:
        - sg-02e861cee93b94d2a
      subnetIds:
        - subnet-073e82f463fce2a4c
        - subnet-0c30b6128a9d398d7
        - subnet-0e9b5194763683428
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_NAME: ${env:DB_NAME}
      DB_USER: ${env:DB_USER}
      DB_PASS: ${env:DB_PASS}
      USER_POOL_ID: ${env:USER_POOL_ID}
      SPOTIFY_ID: ${env:SPOTIFY_ID}
      SPOTIFY_SECRET: ${env:SPOTIFY_SECRET}
    handler: bin/graphql
    events:
      - http:
          path: graphql
          method: post
          authorizer: aws_iam
          cors: true
  admingraphql:
    vpc:
      securityGroupIds:
        - sg-02e861cee93b94d2a
      subnetIds:
        - subnet-073e82f463fce2a4c
        - subnet-0c30b6128a9d398d7
        - subnet-0e9b5194763683428
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_NAME: ${env:DB_NAME}
      DB_USER: ${env:DB_USER}
      DB_PASS: ${env:DB_PASS}
      USER_POOL_ID: ${env:USER_POOL_ID}
      SPOTIFY_ID: ${env:SPOTIFY_ID}
      SPOTIFY_SECRET: ${env:SPOTIFY_SECRET}
    handler: bin/admin_graphql
    events:
      - http:
          path: admin_graphql
          method: post
          authorizer: aws_iam
          cors: true
  postconfirm:
    vpc:
      securityGroupIds:
        - sg-02e861cee93b94d2a
      subnetIds:
        - subnet-073e82f463fce2a4c
        - subnet-0c30b6128a9d398d7
        - subnet-0e9b5194763683428
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_NAME: ${env:DB_NAME}
      DB_USER: ${env:DB_USER}
      DB_PASS: ${env:DB_PASS}
      SPOTIFY_ID: ${env:SPOTIFY_ID}
      SPOTIFY_SECRET: ${env:SPOTIFY_SECRET}
    handler: bin/post_confirm
  automigrate:
    vpc:
      securityGroupIds:
        - sg-02e861cee93b94d2a
      subnetIds:
        - subnet-073e82f463fce2a4c
        - subnet-0c30b6128a9d398d7
        - subnet-0e9b5194763683428
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_NAME: ${env:DB_NAME}
      DB_USER: ${env:DB_USER}
      DB_PASS: ${env:DB_PASS}
      SPOTIFY_ID: ${env:SPOTIFY_ID}
      SPOTIFY_SECRET: ${env:SPOTIFY_SECRET}
    handler: bin/auto_migrate
