AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Used for testing graphql endpoint locally
Resources:
  GraphQlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/graphql
      Runtime: go1.x
      Environment:
        Variables:
          DB_HOST: ${env:DB_HOST}
          DB_PORT: ${env:DB_PORT}
          DB_NAME: ${env:DB_NAME}
          DB_USER: ${env:DB_USER}
          DB_PASS: ${env:DB_PASS}
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
